### ISSUE TITLE
Write-up link returns 404

### ISSUE THREAD

**Issue by ramnamy** [fernando-mc/http-api-cognito-profiles#1]
Hi ,

Thanks for sharing.

However, the write-up link is giving 404.

Could you please check?

https://fernandomc.com/posts/aws-http-api-user-profile-service
![image](https://user-images.githubusercontent.com/34764120/82544466-cad8bc00-9b72-11ea-8b21-215fdb2581a3.png)

**Comment by fernando-mc** [comment]
Great catch! Just fixed it! 
https://fernandomc.com/posts/aws-http-api-cognito-authorizer-python/
